### ISSUE TITLE
Nodes/links don't properly follow the mouse movement

### ISSUE THREAD

**Issue by pb10005** [pb10005/diagram-vue#23]
**Describe the bug**
When in fluid mode, nodes/links don't properly follow the mouse movement; 

**To Reproduce**
1. Check `Toggle fluid` checkbox
2. Turn on edit mode
3. Make the size of the window smaller
4. Drag a node or a link

**Comment by darlandieterich** [comment]
fetch current size: 

this.$refs["thediagrambox"].getBoundingClientRect()

**Comment by pb10005** [comment]
That's what I needed!
Thanks.
