### ISSUE TITLE
How add arrows in links?

### ISSUE THREAD

**Issue by darlandieterich** [pb10005/diagram-vue#3]
Hi! This have support to add arrows in link both ends or only one side? If not what solution?

Great Work!
Thanks.

**Comment by pb10005** [comment]
Hello!
The current version(0.1.9) does not support arrow links, but there's a solution.

As an experiment, I implemented arrow links (pointing just one side) in [this commit](https://github.com/pb10005/diagram-vue/commit/4baf1d753e26a155b31732108ec8bdfea9c6cce6).
See the picture below to check how it looks. 

Thanks for your request.

![snapshot](https://user-images.githubusercontent.com/18681511/64079180-52e60f80-cd1f-11e9-9efb-5dec4a0fa6a1.png)

**Comment by darlandieterich** [comment]
Hello! 
Great work! 
In your new version you can add this options?
You can add parameter to configure arrow in init or end side or both?

I shared your project to many peoples! very useful!
Thanks!

**Comment by pb10005** [comment]
Version 0.1.10 has been released!
This version includes optional arrow links(no direction, one direction, another, or both).

> I shared your project to many peoples! very useful!

I'm really happy to hear that😆

**Comment by darlandieterich** [comment]
@pb10005 much thanks! news will come!!! I can update your documentation??
