### ISSUE TITLE
Click event handler for Node and Link components.

### ISSUE THREAD

**Issue by lesovsky** [pb10005/diagram-vue#39]
I'm trying to make block diagram (like [this](https://3.bp.blogspot.com/-nJ6T8ZckN_A/VkHof_y9-lI/AAAAAAAAAU4/vpG8cfWrp2k/s1600/postgres-observability.png)) and `diagram-vue` is the best component which I found.

I'd like to hide/show blocks (connected with links) when clicking on neighbor blocks. It would be great if `node` component has a something like "@click" event handler which allow to specify user-defined functions.

**Comment by pb10005** [comment]
Thank you for the suggestion! I finished creating click events. see the commit below.
https://github.com/pb10005/diagram-vue/commit/6c24851ee873be736cf256a446e336827d5bdff7

**Comment by lesovsky** [comment]
Thanks, it works!
